### ISSUE TITLE
Named data provider elements not detected when running single test method

### ISSUE THREAD

**Issue by guiyomh** [chiefmyron/phpunit-test-workbench#107]
When I try to run a test, the dataprovider is not taken into account

<img width="745" alt="Capture d’écran 2024-10-10 à 14 43 24" src="https://github.com/user-attachments/assets/02552b12-1d19-4c19-898d-a7c879556912">

**Comment by chiefmyron** [comment]
Hi @guiyomh,

Thanks for getting in touch! Just to confirm a couple of things:
* Does this only occur when trying to execute that specific test? What happens if you try to run all tests in the file?
* Have you made any changes to settings away from the defaults? If so, could you let me know what they are.
* Could you provide a copy of your `phpunit.xml` file please?

If looks like the filter that the extension is using to trigger PHPUnit has some extra characters on the end that I wouldn't expect to see (the filter should be `::should_calculate_balance_with_event$` if you are just running an individual test within a single file.

**Comment by thabo-moyo97** [comment]
![Screenshot 2024-11-28 at 23 58 16](https://github.com/user-attachments/assets/43faf33b-2eb3-4217-b712-381b4f89e974)

Can confirm still happening. Seems the issue is " .*#.*$" on the end of filter. This is incorrect filter, needs to be like so `( .*)?$`

`--filter "/(Tests\\ExampleTest::testDataProviders)( .*)?$/"`

**Comment by chiefmyron** [comment]
Hi @thabo-moyo97 - thanks for the PR! It definitely got me pointed in the right direction, and I can see the problem now - I wasn't taking named data set elements into account. That's in addition to the different string formats depending on the PHPUnit version, as you pointed out.

Hopefully should have a fix pushed out for this soon.
